const tempRoomDatas = [
  {
    room_id: 1,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 2,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 3,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '시스템'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 4,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데이터사이언스', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 5,
    author: 'jongbin',
    title: '공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['게임', '데이터사이언스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 6,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['게임'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 7,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '데브옵스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 8,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데브옵스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 9,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데브옵스', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 10,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데브옵스', '시스템'],
    room_type: 11,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 11,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['게임', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 12,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '게임'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 13,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['게임', '시스템'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 14,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['시스템', '데이터사이언스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 15,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데이터사이언스', '게임'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 16,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데이터사이언스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 17,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '백엔드', '시스템'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 18,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '데이터사이언스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 19,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['데브옵스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 20,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 21,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['시스템', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 22,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['게임', '시스템', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 23,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['백엔드', '데브옵스'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 24,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '시스템'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 25,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 26,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['앱개발', '백엔드'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 27,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['앱개발'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
  {
    room_id: 28,
    author: 'jongbin',
    title: '투썸에서 공부해요',
    expected_users: 6,
    present_users: 1,
    expected_schedules: 60,
    tags: ['프론트엔드', '앱개발'],
    room_type: 1,
    room_status: 'open',
    thumbnail: '/img/tempImage.jpg',
  },
];

export default tempRoomDatas;
